name: Create Archive

on:
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Archive Release
      uses: actions/checkout@master
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'zakat-xe.zip'
        exclusions: '*.git* /*node_*/* *.json *.lock *.md'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'zakat-xe.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
