name: Create Archive

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'zakat-xe.zip'
        path: '.'
        exclusions: '*.git* /*node_*/* *.json *.lock *.md'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'zakat-xe.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
